name: patient_mysql
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^13.0.1
  provider: ^6.1.2
  http: ^1.2.1
  image_picker: ^1.1.2
  path_provider: ^2.1.3
  intl: ^0.19.0
  # ultralytics_yolo_dental: ^1.0.1 # <-- This line MUST BE DELETED or commented out like this!

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/models/dental_best_float16.tflite